### ISSUE TITLE
GARD Ingest

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#109]
## Overview
Create GARD ingest.

## Subtask list
- [ ] 1. Create an ingest repo according to the principles outlined in #2, like you did for omim
- [x] 2. Create a `make all` pipeline that generates gard.owl as a resource
- [ ] 3. Fiddle `gard` into the mondo-ingest pipeline here in this repo, and make sure that mapping, slurping etc works fine
- [x] 4. Take any mappings `gard` already has and convert them to SSSOM and attach them to the release

**Comment by joeflack4** [comment]
@matentzn Whenever you have time, just to clarify, what is meant by "Needs some API calls"? I did a cursory Google search for "gard disease ontology api", but didn't see anything.

**Comment by matentzn** [comment]
I don't know anything about this source, must be some instructions I got from years ago

**Comment by matentzn** [comment]
@joeflack4 can you 

1. Create a GARD ingest repo
2. Add the list provided by Yanji as a Google sheet
3. Modify the Google sheet to become a robot template
4. Create a `Makefile` in the gard ingest repo that translates the ROBOT template pulled from the Google docs into OWL
5. Add some way to run a release - no need for a GH action.

**Comment by matentzn** [comment]
- [ ] Make a new issue that covers Eric Sids request: "If you can please let us know which GARD concepts are currently used by MONDO but are missing from this list, we can note those on a prioritized list for manual curation/validation."

**Comment by joeflack4** [comment]
At this stage, I'm almost done with all the tasks mentioned in the OP, and I also completed all of the tasks mentioned in [this comment](https://github.com/monarch-initiative/mondo-ingest/issues/109#issuecomment-1497272114), with the possible exception of "run a release".

If "run a release" means the script should put into a GitHub release, then I haven't done that. That'd be just as easily done through a GitHub action. But I think what Nico means is to simply ensure that `make all` generates all of the artefacts, and possibly that it also commits them. That is what I have done. I've also decided that for these kinds of outputs, if we are committing them, it's best to put them in a folder called "release". My idea is that 100% of the files that are committed there (assuming they're not so big that they require Git LFS) are will also be manually uploaded as GitHub releases.

**Comment by matentzn** [comment]
This is great! Can you 

1. add a deploy-release goal to the GARD makefile
2. add a gard release that attaches all files of relevance (sssom, owl) with a `v2023-01-01` type tag
3. Include the GARD ingest in the general ingest here?

**Comment by joeflack4** [comment]
Very close to having (2) and (3) done. It sounds like (1) in the comment above is the same as (5) in [this comment](https://github.com/monarch-initiative/mondo-ingest/issues/109#issuecomment-1497272114). But I'm not entirely clear on this. It sounds like you want a makefile goal that interacts with the GitHub API to make a release, and you'd prefer that to a GitHub action. But this would be the first that we've done such a thing, so I'm not sure if I'm understanding correctly. I'm not opposed to it, but I should add that a GitHub action would be quicker/easier for me to do and has the added benefit of being able to be run by any of us more easily.

**Comment by matentzn** [comment]
I was thinking for something like https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/mondo-ingest.Makefile#L326 for (1)?

**Comment by joeflack4** [comment]
Oh, I didn't even see that you added that. I've never used the GitHub CLI. Didn't know that it had a really command. That looks awesome and easy to use! Will do
