### ISSUE TITLE
Slurp: Deprecation updates

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#116]
## Overview
There are some obsolete/deprecated OMIM terms that made their way into Mondo. Perhaps there is still some work to be done on the slurp?

## Sub-task list
- [x] 1. Figure out how to identify deprecated terms in OMIM, if not already
- [x] 2. Make sure they are labeled as such in the output
- [ ] 3. Make sure this information is slurped: We basically need (i) a list of all deprecated OMIM terms for now, and (ii) their replacement if any

## Related
- #74 
- https://github.com/monarch-initiative/mondo/issues/5640
- https://github.com/monarch-initiative/omim/issues/87

**Comment by joeflack4** [comment]
@matentzn You [mentioned](https://github.com/monarch-initiative/mondo/issues/5640#issuecomment-1330481017) that some deprecation slurp code needs to be updated/prioritized. Not sure what to do yet, but for now, just creating this issue and adding to the board so can be on my radar.

**Comment by matentzn** [comment]
Actually we have not synced deprecation status with OMIM in.. years. So this will be a high value new feature!

**Comment by matentzn** [comment]
We basically need a list of all deprecated OMIM terms for now, and their replacement if any.

**Comment by joeflack4** [comment]
Looks like the OMIM ingest side of things is done. Example: 
```owl
OMIM:102590 a owl:Class ;
    IAO:0100001 OMIM:614413 ;
    owl:deprecated true .
```

How it's identified (`mimTitles.txt`):
```tsv
Prefix	MIM Number	Preferred Title; symbol	Alternative Title(s); symbol(s)	Included Title(s); symbols
Caret	102640	MOVED TO 102630
```
