### ISSUE TITLE
ICD11 ingest: grouping issue

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#16]
## Overview
Ingest ICD11 into Mondo.

## Sub-task list
- [x] 1. Ingest ICD11 source  #434 @joeflack4 
- [x] 2. https://github.com/monarch-initiative/icd11/issues/10 / https://github.com/monarch-initiative/icd11/pull/12 @joeflack4 
- [x] 3. #140 @hrshdhgd 
- [x] 4. Close https://github.com/monarch-initiative/mondo/issues/1107 when all tasks above are complete

## 1. Ingest ICD11 source
Add ICD 11 foundation as a regular sync source in ODK / `mondo-ingest.Makefile`.

<details><summary>How to get data via REST API (defunct)</summary>
<p>
Defunct because we now have an `.owl` to work with.

From Can Celik (WHO):
> As Chris mentioned, we have a REST API for the ICD11 which gives access to the foundation component of the ICD-11 as well the linearizations (i.e. statistical classification). It contains additional functionality on top of providing full access to the classification. For example, the API contains search endpoints powered by our search engine which could be useful for mapping projects. The API supports JSON-LD, it is multilingual which contains 5 languages at the moment, and also provides access to earlier releases of the classification. More information on it could be found in our ICD-API Home Page https://icd.who.int/icdapi

And: 
> At this point, we don’t have a file that would be suitable for you. We have basic files with codes, titles, etc. but not something that includes more than that.
Reading everything won’t be a problem. The API is rather efficient. Also, you could easily deploy a local version if you prefer. With Docker, it’s just one command or several clicks to install it as a Windows or a Linux service.
We’ve just released new versions yesterday.

</p>
</details> 

## 2. ICD11::ORDO mappings
Get ahold of all ICD11 - ORDO mappings from a respectable source and derive an initial set of Mondo - ICD11 mappings from that (with the mapping set id as the source)

From Julie at Orphanet:
> ICD-11 is included into ORDO (release every 6 months) but only the MMS code is represented. If you need URI (from the Foundation) and MMS aligned codes, you need to download the alignment file on Orphadata or the nomenclature pack.  Initially, we have designed a two-step process. The first phase has consisted to perform a lexical/semantical semi-automatic mapping to align all the entites represented in the foundation and/or the MMS; this is almost completed. The second phase has started several months ago and consists to attribute a MMS code for the rare diseases not represented in ICD-11. Up to date, the coverage is 65,8% for the disorder level (percentage calculated on active entities and for all relationships). We are actively working to improve the coverage but as you can imagine, it is very long.

**Comment by joeflack4** [comment]
See relevant PR: https://github.com/monarch-initiative/mondo-ingest-private/pull/1

**Comment by matentzn** [comment]
FYI @joeflack4 updated the description above with a quote from Orphanet:

> ICD-11 is included into ORDO (release every 6 months) but only the MMS code is represented. If you need URI (from the Foundation) and MMS aligned codes, you need to download the alignment file on Orphadata or the nomenclature pack.

**Comment by joeflack4** [comment]
Oh, thanks. I forgot about those mappings. Right now I'm focused on _1. ICD11 source_ rather than  _2. ICD11::ORDO mappings_. If you want, I can kinda do them in parallel too. Right now I'm not sure where to get that ORDO release. Maybe here?: https://www.orphadata.com/orphanet-nomenclature-for-coding/

Sounds like she's saying right now they only have ICD11 MMS(Morbidity and Mortality) terms, but they'll soon also have (the rest of the) foundation terms, as well as a list of Orphanet diseases not mapped to ICD11.

**Comment by matentzn** [comment]
I think ICD11:ORDO can be done as a second PR - just to keep things as small as possible, but it should be done (1) before this ticket is closed, and (2) before someone starts with the manual curation process.

**Comment by joeflack4** [comment]
@matentzn I set myself a reminder for when wrapping #434 to evaluate this. Feel free to think about this and respond now if you like. I'm adding it to the agenda for our next meeting though, so we can also discuss then.

**Comment by matentzn** [comment]
Think about what exactly?

**Comment by joeflack4** [comment]
@matentzn Sorry I meant think about "to evaluate this" (issue). As in where these are in the priorities, as well as expanding on (2). Actually, let's just leave this to the next meeting; we'll have a better idea then after I've made progress on other issues.

**Comment by joeflack4** [comment]
Complete!
