### ISSUE TITLE
NCIT: `OutOfMemoryError` (can't update `ncit.owl` or exclusions)

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#192]
## Overview
Was recently able to fix [an out of memory error for mirror_sig](https://github.com/monarch-initiative/mondo-ingest/issues/171) by switching to OAK. For now this is the only good idea we have for solving this more generally. The result may entail a broad OAK-ification refactor of various scripts since we can (and should) re-use that logic not just for NCIT, but for the other ontologies.

## Sub-task list
- [ ] 1. Fix issue for exclusions
- [ ] 2. Fix issue for `components/ncit.owl`
- [ ] 3. Fix issue anywhere else in pipeline (not sure where if any)

### 1. Fix issue for exclusions
This just entails switching from `robot` calls to OAK.

Would fix `OutOfMemoryError`: [log.txt](https://github.com/monarch-initiative/mondo-ingest/files/10727239/log.txt)

### 2. Fix issue for `components/ncit.owl`
[ncit-error.txt](https://github.com/monarch-initiative/mondo-ingest/files/10819524/ncit-error.txt)

See [discussion below](https://github.com/monarch-initiative/mondo-ingest/issues/192#issuecomment-1442603918).

## Additional details
We tried solving with a very reasonable 20GB of memory in our ODK image, but to no avail:
<img width="863" alt="216852883-eb51646e-b6fd-4a95-913d-bab97cb35171" src="https://user-images.githubusercontent.com/13045020/218599599-e4cab022-a37a-40be-bd3e-2f6a9d1ecf2b.png">

**Comment by joeflack4** [comment]
@matentzn I was rerunning the [slurp today](https://github.com/monarch-initiative/mondo-ingest/pull/210) and, as I suspected might happen, NCIT failed with an out of memory error. 

Here's the part that's hard for me. It failed on `components/ncit.owl`. Up until now, the `components/*.owl` file is what I need to even begin to start using OAK with `mondo-ingest`.

Do you have any ideas as to how I might get around this problem? Should I/we do something like this:
#### Option A
i. Start with `component-download-ncit.owl.owl`
ii. Rewrite the goal for `components/ncit.owl` to one that uses OAK, if that's possible (possibly a heavy lift?)

#### Option B
Use `component-download-ncit.owl.owl` instead of `components/ncit.owl` if that is not a terrible idea.

[ncit-error.txt](https://github.com/monarch-initiative/mondo-ingest/files/10819521/ncit-error.txt)

**Comment by matentzn** [comment]
Hm, neither is great, its such a pity we need that much more memory now. 

Solution, when running locally, you can now [skip NCIT](https://github.com/monarch-initiative/mondo-ingest/commit/813edc1b2e83f8b0abe1042097acd955d4902b8c).

```
sh run.sh make SKIP_HUGE=true slurp
```

**Comment by joeflack4** [comment]
Darn, I see. Ok, I'll do that for now~

**Comment by joeflack4** [comment]
@matentzn It looks like this isn't working, because even though you've added `SKIP_HUGE` to `mondo-ingest.Makefile` `components/ncit.owl`, this exists in the `Makefile`:

```
.PHONY: component-download-ncit.owl
component-download-ncit.owl: | $(TMPDIR)
	if [ $(MIR) = true ] && [ $(COMP) = true ]; then $(ROBOT) merge -I http://purl.obolibrary.org/obo/ncit.owl \
	annotate --ontology-iri $(ONTBASE)/$@ $(ANNOTATE_ONTOLOGY_VERSION) -o $(TMPDIR)/$@.owl; fi

$(COMPONENTSDIR)/ncit.owl:  component-download-ncit.owl
	if [ $(COMP) = true ] ; then if cmp -s $(TMPDIR)/component-download-ncit.owl.owl $@ ; then echo "Component identical."; else echo "Component is different, updating." && cp $(TMPDIR)/component-download-ncit.owl.owl $@; fi; fi

.PRECIOUS: $(COMPONENTSDIR)/ncit.owl
```

I was imagining that running `sh run.sh make SKIP_HUGE=true components/ncit.owl` would skip it, but it went to run the goal  with the same name in the `Makefile` anyway.

FYI I have the latest version of ODK full downloaded. Updating ODK dev now.

If there are any other updates you need to do to make this skipping work and you have time, that's fine. But I have other ways to circumvent NCIT if I need to.

**Comment by joeflack4** [comment]
@matentzn Also, is there a logic error here?

```make
$(COMPONENTSDIR)/ncit.owl: $(TMPDIR)/ncit_relevant_signature.txt
	if [ $(SKIP_HUGE) = true ] && [ $(COMP) = true ]; then $(ROBOT) remove -i $(TMPDIR)/component-download-ncit.owl.owl ...
```

Should this not be `if [ $(SKIP_HUGE) = false ] ...` instead?

**Comment by matentzn** [comment]
Yes its reversed!
Can you change? That should fix it

**Comment by joeflack4** [comment]
@matentzn Yes I will change it and push to `main` now.

Looks like you're right. I was wrong about [this comment](https://github.com/monarch-initiative/mondo-ingest/issues/192#issuecomment-1444527318); if I use `IMP=false COMP=false MIR=false`, it doesn't still run that goal in `Makefile`.

**Comment by joeflack4** [comment]
@matentzn @twhetzel I'm going to close this issue, as none of us who are running the build are encountering this anymore.

**ROBOT / docker confusion**
I am confused though, as even though we can allocate a lot of memory to Docker, this supposedly does not apply to ROBOT (context: [Slack](https://obo-communitygroup.slack.com/archives/C01BKKED8R2/p1718874334449919?thread_ts=1718858972.921809&cid=C01BKKED8R2)), and the memory for that has to be set via `robot_java_args` in `mondo-ingest-odk.yaml`, which currently is set to `'-Xmx20G'`. And 20GB was not enough to run NCIT previously, so either (a) At some point, NCIT began to run in ROBOT using less memory, or (b) somehow ROBOT is able to use >20GB despite this.

FYI max memory usage during my last build was around 33GB, though I don't know which command it was where this happened.

**Comment by matentzn** [comment]
I noticed that since I have my M3, I require about 20% less memory for most tasks. Maybe it’s related
