### ISSUE TITLE
Slurp: Deprecation updates

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#196]
## Overview
**This should apply for all ontologies**
There are some obsolete/deprecated OMIM terms that made their way into Mondo. Perhaps there is still some work to be done on the slurp?

## Sub-task list
- [x] 1. Figure out how to identify deprecated terms in OMIM, if not already
- [x] 2. Make sure they are labeled as such in the output
- [x] 3. Make sure this information is slurped

### Sub-task details
: We basically need (i) a list of all deprecated OMIM (should work for any ontology) terms for now, and (ii) their replacement if any
Will need to look at the `mirror/` files to see how replacements are marked, if any. In Mondo, they're like this `<obo:IAO_0000111 xml:lang="en">term replaced by</obo:IAO_0000111>`. The most important things are (i) to do this for OMIM, although general would be best, (ii) look for if replaced by, but could well be nothing for other ontologies. Ideally we would re-use the deprecated analysis recently done, but that depends on `mapping_status.tsv`, which is only gotten by querying `components/`, because OAK errors on querying `mirror/`. 

NCIT, OMIM & DO all have proper deprecation status in `components/`.
For [ORDO](https://github.com/monarch-initiative/mondo-ingest/pull/186/files), there is an 'inactive' tree, which we've also excluded. This contains deprecated terms.

There may not be any replacements for any ontology.

Merging this: https://github.com/monarch-initiative/mondo-ingest/pull/194/files and then can continue to use this pipeline.

Output should be a robot template `%_deprecated_replacements.tsv`. How formatted? 
```tsv
source_id	replacement	replacement_predicate?
ID	ID	???
myOntology:123	myOntology:456	obo:IAO_0000111
```

## Related
- https://github.com/monarch-initiative/mondo/issues/5640
- https://github.com/monarch-initiative/mondo-ingest/issues/74
- https://github.com/monarch-initiative/mondo-ingest/issues/116
- https://github.com/monarch-initiative/mondo-ingest/pull/108
