### ISSUE TITLE
DECIPHER ingest

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#244]
## Overview
Create DECIPHER ingest.

## Sub-task list
Some of these are copy/pasted from other ingest issues, so I don't know if 100% of them apply here.
- [ ] 1. Create an ingest repo according to the principles outlined in #2, like you did for omim
- [ ] 2. Create a `make all` pipeline that generates decipher.owl as a resource, if it exists
- [ ] 3. Fiddle `gard` into the mondo-ingest pipeline here in this repo, and make sure that mapping, slurping etc works fine
- [ ] 4. Take any mappings `decipher` already has and convert them to SSSOM and attach them to the release

## Additional information
Data source(s)
https://www.deciphergenomics.org/
> Nico: I don't know what the best way to obtain DECIPHER is, this will require some reaching out to Chris and googling.. Thanks!

Related to:
- #242

**Comment by joeflack4** [comment]
Unassigning myself on this one, per decision at meeting. Low / no priority.
