### ISSUE TITLE
Bug: Sync subclass: ancestor inconsistencies

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#406]
## Overview
Nico was trying to fix some bugs in the pipeline (#403) when he noticed [an issue regarding ancestor inconsistencies](https://github.com/monarch-initiative/mondo-ingest/pull/403/files#r1467619776). Basically, we expect that `ancestor()` edges should give the same results as the indirect edges + direct edges. But we're getting an error where that is not the case.

## Sub-tasks
- [ ] 1. Find root cause of issue & fix
  - May include #408
- [ ] 2. Consider changing back: `logging.error()` -> `raise ValueError()`
- [ ] 3. Change logger to print info?

### 3. Change logger to print info?
<details><summary>Details</summary>
<p>

This is unrelated to this issue, but basically I was expecting `logging.info()` to print, but it is not. It would help me to debug if this would print. Should we print these? Should we change these to `logging.debug()` and maybe I change my code so that if I'm running what I typically run in the debugger, `run_defaults()`, it sets the logging to debug mode?

Shamefully I don't have enough experience with logging. I tried to fix with some suggestions [here](https://stackoverflow.com/questions/7016056/python-logging-not-outputting-anything), but most of what I tried didn't work (nor did ChatGPT work). One suggestion did work, but it ended up printing everything twice.

</p>
</details>

**Comment by joeflack4** [comment]
@matentzn Frustratingly, I can't replicate your issue. I probably screwed up somewhere along the way. Maybe you can figure it out? Here's what I tried.

## What I did
### Setup 1: My current `mondo-ingest` clone
1. Branch off of your [`reinstate-sync` PR](https://github.com/monarch-initiative/mondo-ingest/pull/403/)
2. Make new branch / [PR `bug-sync-ancestor`](https://github.com/monarch-initiative/mondo-ingest/pull/408)
3. Add [`%.db` bugfix I suggested](https://github.com/monarch-initiative/mondo-ingest/pull/403/files#r1468197406). Otherwise it was erroring out for me as expected.
4. `rm src/ontology/reports/*subclass*`
5. `Deleted and remade subclass prereqs `tmp/mondo-ingest.db tmp/mondo.db tmp/mondo.sssom.tsv`
  - Pretty sure I did this without also adding `IMP=false COMP=false MIR=false`. I know at least they changed somehow because I backed them up first and I just checked `md5` and they are different.
7. Tried running in both (i) debugger, and (ii) through ODK with `IMP=false COMP=false MIR=false`

### Setup 2: Fresh `mondo-ingest` clone
1. Fresh `git clone`
2. Check out my `bug-sync-ancestor` branch (with bugfix in step (3) above) from 'setup 1'.
3. `rm src/ontology/reports/*subclass*`
4. Ran just through ODK `sh run.sh make sync`

## Questions
1. Can you tell me anything that would help me replicate [your issue](https://github.com/monarch-initiative/mondo-ingest/pull/403/files#r1467619776)?
2. What source was running when that error happened, if you remember?

**Comment by matentzn** [comment]
I will rerun it again now and see if it was a de-synchronised issue on my end.. I noticed another issue which I caused (missing pip install). So if all goes well, we can just merge this and we are good again!

**Comment by joeflack4** [comment]
@matentzn Assigned this one to you now! If you re run and there's no issue feel free to close.

**Comment by matentzn** [comment]
Yes this was fixed a few PRs ago! Thanks for ping, closing.
