### ISSUE TITLE
ICD11: Identify disease roots

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#449]
## Overview
Joe has made an [initial selection](https://github.com/monarch-initiative/mondo-ingest/pull/412#discussion_r1493476512) of `icd11.foundation:455013390` (_ICD Category_) as the sole root for disease terms for ICD11. However, he is not sure if this is correct. It may be that there may be other diseases which fall under other categorical terms. So we should check if this selection is correct.

## Sub-tasks
- [ ] 1. Identify correct root(s)
- [ ] 2. Possible SPARQL updates
If Joe's initial selection was not correct, then `sparql/icd11foundation-relevant-signature.sparql` should be updated with the correct root(s).
- [ ] 3. Possible exclusions updates
There might be some non-disease terms that fall under `icd11.foundation:455013390` (or other disease roots, if there are any). In which case, the thing to do would be to add entries into `config/icd11foundation_exclusions.tsv`, but I don't think that is in scope for this issue, so the task here would be to create a new issue probably.

## Additional details
<details><summary>Protégé tree screenshot</summary>
<p>

<img width="550" alt="icd11 foundation tree" src="https://github.com/monarch-initiative/mondo-ingest/assets/13045020/43377e13-7d40-4f5e-8c3e-8ab93b01f656">

</p>
</details>
