### ISSUE TITLE
ICD11 properties: `narrowerTerm`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#461]
## Overview
Need to figure out what to do with this annotation property.

## Sub-tasks
- [x] Provide examples of usage @joeflack4 
  - [x] Perhaps propose a recommendation @joeflack4 
- [x] Decide what to do @matentzn and/or @twhetzel 

### The nature of `narrowerTerm`
I did some checking, and now I see that this is not actually an object property for other terms, **but an annotation property which holds a label**, and the label does not exist on any other term.

<details><summary>Details</summary>
<p>

#### Facts
Some new things I've learned based on looking at a few examples.

1. **Not an object property for other terms, but an annotation property which holds a label**
2. **The label in `narrowerTerm` does not appear anywhere else in the ontology**
3. **Sometimes, there is an `inclusion` property which has the exact same value (label) as `narrowerTerm`**: See _example 2_.
4. **Is multivalued**: See _example 3_. It has 10 `narrowerTerm` entries.

It looks to me like `narrowerTerm` is not simply an `altLabel`. It appears to me that the `narrowerTerm` entries are actually more general/broader / less specific than the term (indicated by its label) itself. I'm not 100% sure of that though; maybe I'm wrong, or maybe that's not case 100% of the time. I'm trying to guess why these properties are here, and why they are static labels rather than references to other classes; perhaps these are placeholders for future possible classes to be added. It seems like a strange and fraught practice to do that. Perhaps we need to ask the WHO about this.

Example 1
```owl
    <owl:Class rdf:about="http://id.who.int/icd/entity/1000312374">
        <rdfs:subClassOf rdf:resource="http://id.who.int/icd/entity/1345372703"/>
        <schema:browserUrl rdf:resource="https://icd.who.int/dev11/f/en#/http%3A%2F%2Fid.who.int%2Ficd%2Fentity%2F1000312374"/>
        <schema:isObsolote rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</schema:isObsolote>
        <schema:narrowerTerm xml:lang="en">idiopathic; hematuria, with glomerular lesion, membranous (diffuse)</schema:narrowerTerm>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
        <skos:definition xml:lang="en">This refers to recurrent and persistent presence of red blood cells (erythrocytes) in the urine. This diagnosis is with a slowly progressive disease of the kidney affecting mostly patients between ages of 30 and 50 years, usually Caucasian.
</skos:definition>
        <skos:prefLabel xml:lang="en">Recurrent and persistent haematuria : diffuse membranous glomerulonephritis</skos:prefLabel>
    </owl:Class>
```

Example 2
```
    <owl:Class rdf:about="http://id.who.int/icd/entity/1002516273">
        <rdfs:subClassOf rdf:resource="http://id.who.int/icd/entity/708418764"/>
        <schema:browserUrl rdf:resource="https://icd.who.int/dev11/f/en#/http%3A%2F%2Fid.who.int%2Ficd%2Fentity%2F1002516273"/>
        <schema:inclusion xml:lang="en">Superficial thrombophlebitis of unspecified site</schema:inclusion>
        <schema:isObsolote rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</schema:isObsolote>
        <schema:narrowerTerm xml:lang="en">Superficial thrombophlebitis of unspecified site</schema:narrowerTerm>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
        <skos:definition xml:lang="en">This is a thrombosis and inflammation of superficial veins which presents as a painful induration with erythema, often in a linear or branching configuration forming cords, of other sites.
</skos:definition>
        <skos:prefLabel xml:lang="en">Superficial thrombophlebitis of other sites</skos:prefLabel>
    </owl:Class>
```

Example 3
```
example 3
    <owl:Class rdf:about="http://id.who.int/icd/entity/1003298671">
        <rdfs:subClassOf rdf:resource="http://id.who.int/icd/entity/1458150337"/>
        <schema:browserUrl rdf:resource="https://icd.who.int/dev11/f/en#/http%3A%2F%2Fid.who.int%2Ficd%2Fentity%2F1003298671"/>
        <schema:isObsolote rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</schema:isObsolote>
        <schema:narrowerTerm xml:lang="en">inflammation of vein</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">phlebitis</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">phlebitis infective</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">phlebitis septic</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">pyemic phlebitis</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">thrombophlebitis</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">thrombotic vein inflammation</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">thrombotic venous inflammation</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">ulcerative phlebitis</schema:narrowerTerm>
        <schema:narrowerTerm xml:lang="en">venous inflammation</schema:narrowerTerm>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
        <skos:prefLabel xml:lang="en">Phlebitis and thrombophlebitis of unspecified site</skos:prefLabel>
    </owl:Class>
```

</p>
</details> 

### Context

**From [property discussion thread](https://github.com/monarch-initiative/mondo-ingest/pull/434#discussion_r1483728680):**
Joe:
> I'm not sure if these map to anything outside of ICD11. If they don't, should we simply ignore?
> I imagine `narrowerTerm` is either `skos:narrowMatch` or `skos:broadMatch`.

Nico:
> ignore for now and make separate issue with examples

**Comment by matentzn** [comment]
I personally think we should ditch entirely - I dont see a real value of narrow and broad anythings in ETL.

**Comment by joeflack4** [comment]
@matentzn Got it. I haven't created my own `robot remove` commands before, but I figured out what I needed:
```owl
icd11test.owl:
	$(ROBOT) remove -i $(COMPONENTSDIR)/icd11foundation.owl --term http://id.who.int/icd/schema/narrowerTerm --select "annotation-properties" -o $@
```

I was pleasantly surprised to see that this actually ended up also removing the class declaration after removing all annotation property instances.

---

@matentzn However, some new information has come to light. Before I remove these, I'd like you to look in the OP at the _details_ in _Additional details > The nature of `narrowerTerm`_. After reading that, let me know what you think I / we should do.

**Comment by matentzn** [comment]
@joeflack4 Thank you for being persistent. In this case, I change my _assessment_ (not strategy):

http://id.who.int/icd/schema/narrowerTerm _could_ be mapped to `http://www.geneontology.org/formats/oboInOwl#hasBroadSynonym`. (careful, _not_ narrow, as they have the direction backwards, and we dont use altLabel in our data model). 

However, I still maintain that this mapping should be _use case driven_. I am not personally that interested in "narrow" and "broad" synonyms, so I personally maintain that we _should right now not import this, and have it removed with ROBOT remove as you have done already_.

**Comment by joeflack4** [comment]
I'm in agreement with all of that! I'll do the  `robot remove` momentarily.
