### ISSUE TITLE
ICD11 properties: `inclusion`/`exclusion`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#462]
## Overview
Need to figure out what to do with these annotation properties.

## Sub-tasks
- [ ] Provide examples of usage @joeflack4 
  - [ ] Perhaps propose a recommendation @joeflack4 
- [ ] Decide what to do @matentzn and/or @twhetzel 

## Additional details
<details><summary>Context</summary>
<p>

**From [property discussion thread](https://github.com/monarch-initiative/mondo-ingest/pull/434#discussion_r1483728680):**
Joe:
> inclusion: take a look. include but also put inside rdfs:comment?
> exclusion: take a look. include but also put inside rdfs:comment?

Nico: 
> Make separate issue with examples. (PRs are not great for this)

</p>
</details>

**Comment by joeflack4** [comment]
I'm not 100% sure, but at face these appear  to me to be a way, to add additional modifications beyond a normal subclass relationship. You mark something a subclass of another, but then it might inherit some other relationships which then you can mark with `exclusion`. And then perhaps you can mark `inclusion` for some other classes that do not have a subclass relationship.

For now, I've added more details in this comment: https://github.com/monarch-initiative/mondo-ingest/pull/434#discussion_r1510434552
