### ISSUE TITLE
ICD11 properties: Definition related

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#463]
## Overview
Need to figure out what to do with these annotation properties.

## Sub-tasks
- [x] 1. Tasks for #434
- [x] 2. Perhaps provide examples of usage @joeflack4 
- [x] 3. Perhaps propose a recommendation @joeflack4 
- [x] 4. Decide what to do @matentzn and/or @twhetzel 

## Additional details: Context
**From [property discussion thread](https://github.com/monarch-initiative/mondo-ingest/pull/434#discussion_r1483728680):**
Joe:
> Props they have:
> - http://www.w3.org/2004/02/skos/core#definition
> - `longDefinition`
> 
> Possible solutions:
> a. Combine both and put into `IAO:0000115`
>   Add subheaders?: "short definition" and "long definition"?
> b. Put one into `IAO:0000115`, and include the other using its original predicate, or add it to `rdfs:comment`

Nico:
> Very important, and hard to answer. I think separate issue, for now make `skos:definition` to `IAO:0000115` but in issue, suggest what you want for the `longDefinition`.

**Comment by matentzn** [comment]
A comment on your use of `<details>`: While I love the tidyness of display it gives, the only makes sense if the issue or comment can be addressed without opening `<details>`.  You hide critical information in `details` which means I keep having to open it no matter what.

As for this issue: Can you provide 3 examples of skos:definition / longDefinition pairs?

**Comment by joeflack4** [comment]
Yeah I saw your message [on Slack](https://monarchinitiative.slack.com/archives/C0222P0736F/p1709535799281999) as well, NP.

Will provide those examples soon!

**Comment by joeflack4** [comment]
## Examples
### http://id.who.int/icd/entity/1364737590: Inflammatory pseudotumour of liver
`skos:definition`: Inflammatory pseudotumour of the liver is a rare benign tumour-like lesion. There are two clinical presentations: the active form most commonly manifests with abdominal pain, fever and loss of body weight; and the form called solitary necrotic tumour that is usually clinically silent.

`icd11.schema:longDefinition`: Inflammatory pseudotumor (IPT) of the liver is a rare benign tumor-like lesion.
Approximately 140 cases have been reported worldwide, with a higher prevalence for male adults of Asian origin and subjects affected by systemic diseases such as rheumatoid arthritis. Some cases of IPT of the liver have been associated with extrahepatic malignant tumors. There are two clinical presentations.
The active form most commonly manifests with abdominal pain, fever and loss of body weight.
Laboratory findings include an increased erythrocyte sedimentation rate (ESR) and increases levels of C-reactive protein (CRP), leukocytosis, slightly elevated aminotransferase activity, increased bilirubin levels and variable alterations of the electrophoretic pattern. 
Histologically, ITP of the liver is characterized by a large population of polyclonal plasma cells with a variable amount of fibrosis, foamy histiocytes and other chronic inflammatory cells. On imaging, the lesion is often large and mimics malignant liver tumors. The second form (also described as solitary necrotic tumor) is usually clinically silent. Blood liver tests are normal and there are no remarkable laboratory findings. On imaging, the lesion is well-limited and may be surrounded by a capsule. 
The etiopathogenesis of IPT of the liver remains unclear. Recent publications suggested either a post-inflammatory regenerative process (caused by bacteria from food, chronic appendicitis or cholecystitis, or Epstein-Barr virus infection) or a primary neoplastic process. The clinical picture, imaging and macroscopic appearance of IPT of the liver are similar to those of other hepatic pathologies, including malignant liver tumors: granulomatous hepatitis, liver abscess, sarcoidosis (see this term), hepatic tuberculosis, hepatocellular carcinoma (see this term), cholangiocellular carcinoma (see this term), and metastatic liver tumor.
Diagnosis is important to avoid surgery and requires a histological confirmation (percutaneous biopsy). There is no standardized optimum management. Surgical resection (partial hepatic resection) was usually performed because the diagnosis was rarely made prior the surgery. However, regression is the rule with antibiotics. Spontaneous regression has also been described. 

Things long definition has which definition does not: 
- **Synonyms**: Includes one (IPT). That's if acronyms are considered synonyms; I'm not sure.
- **Rarity**: "140 cases worldwide"
- **Typical population**: "male adults of Asian origin and subjects..."
- **Diagnostic info**: Describes typical lab findings, etc
- **Histology**
- **Etiopathogenesis**
- **Optimum management**: Or rather lack thereof
- **Disease regression**
- **Treatment; historical info**: surgical resection

### http://id.who.int/icd/entity/136519310: Interstitial or deep keratitis
`skos:definition`: This is an inflammation of the cornea that results in corneal scarring due to invasion of blood vessels into the corneal stroma as part of the inflammatory response. Syphilis is the leading cause of this process.

`icd11.schema:longDefinition`: This refers to corneal scarring due to chronic inflammation of the corneal stroma. Interstitial means space between cells i.e. corneal stroma which lies between the epithelium and the endothelium. Keratitis means corneal inflammation.

Things long definition has which definition does not: 
- **Adds missing qualifier**: `longDefinition` qualifies that cause is due to _chronic_ inflammation, which `skos:definition` does not. I think this is just an oversight in the `skos:definition`, and it should ideally belong there.
- **Contextual definitions**: For "Interstitial" and "Keratitis". I don't think this information is super useful.

### http://id.who.int/icd/entity/1365585570: Chagas disease
`skos:definition`: A disease caused by an infection with the protozoan parasite Trypanosoma cruzi. This disease is characterised by fever, headache, lymphadenopathy, pallor, muscle pain, dyspnoea, swelling, or abdominal or chest pain. This disease may also be asymptomatic. Transmission is by direct contact with faeces from an infected triatomine bug, vertical transmission, iatrogenic transmission, or ingestion of contaminated food or water. Confirmation is by identification of Trypanosoma cruzi in a blood sample.

`icd11.schema:longDefinition`: Chagas disease, also known as American trypanosomiasis, is caused by infection with the protozoan parasite Trypanosoma cruzi. T cruzi is found mostly in blood sucking triatomine insects (kissing bugs) and small mammals in a sylvatic cycle that is enzootic from the southern and southwestern United States to central Argentina and Chile. T cruzi infection in humans occurs in a spotty distribution throughout the range of the sylvatic cycle. T cruzi infection is life-long. A minority of persons with long-standing T cruzi infection develop the serious cardiac and gastrointestinal problems that characterize chronic symptomatic Chagas disease.

Things long definition has which definition does not: 
- **Synonyms**: Includes one (American trypanosomiasis)
- **Etiology context**: information about the parasite and how/where transmission can occur
- **Duration**: life-long
- **Subclass info**: Mentions / describes a "subclass" (chronic symptomatic Chagas disease). However there is no ICD11 class for this.


## Overall thoughts
There's definitely a lot of usefulu information in the `longDefinition`.

Options: 
a. Keep as`icd11.schema:longDefinition`?: Easy and keeps information grannular, but isn't very good in terms of harmonization.
b. Convert to / include in `rdfs:comment`?: Maybe a good option, but I don't really know if there is nuance in how `rdfs:comment` is generally used or particularly used in Mondo.
c. Append to `skos:definition`?: I don't know if I like this option, as (i) this creates a mismatch in our `skos:definition` and that of the source, and (ii) some of the content in `longDefinition` is, in my opinion more contextual than definitional.
d. Drop it: I don't like this option because it is lossy and fron what I can gather, there is some useful / important information in these long definitions.
e. `dcterms:description`?: [ChatGPT suggested](https://chat.openai.com/share/0a702d4c-317a-472b-9620-dd1e6b175929) possibly using.
e. Some other annotation property?

**Comment by matentzn** [comment]
either using dcterms:description or rdfs:comment is fine by me! Great analysis.

**Comment by joeflack4** [comment]
Thanks~. I think I like `dcterms:description`.
