### ISSUE TITLE
Create ORDO subset ROBOT template - updates

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#515]
## Overview
In #510, we successfully created a robot template that updated ORDO rare disease subsets. We will need to re-run this in the future, but there are a few updates that need to be made.

## Sub-tasks
- [x] 1. [Utilize `curies`](https://github.com/monarch-initiative/mondo-ingest/pull/510#discussion_r1588599257)
- [x] [2](https://github.com/monarch-initiative/mondo-ingest/pull/510#pullrequestreview-2039368784). `reports/ordo-subsets.robot.template.tsv` would be moved to where NORD external content is located (`src/ontology/external` I think) as we should consider this template "externally managed content"
- [x] [3](https://github.com/monarch-initiative/mondo-ingest/pull/510#pullrequestreview-2039368784). We can make sure its processed as part of the general `build-mondo-ingest` pipeline

**Comment by joeflack4** [comment]
Marking this 'very high' priority just because it's `ease:high`.

**Comment by joeflack4** [comment]
@twhetzel In order to do the build #543, I needed to do tasks (2) and (3) in this issue, so I went ahead and just did all 3 of them while I was at it in my [latest commit](https://github.com/monarch-initiative/mondo-ingest/pull/510/commits/ca64342c390e538b8d12cf425672cf8c5ff22977).

**Comment by joeflack4** [comment]
Addressed by:
- #510
