### ISSUE TITLE
Build quality - minor questions / concerns

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#575]
## Overview
We just did a new build, and I noticed some things that seemed a little off. I don't think they're major, but worth looking into at some point.

## Sub-tasks
Some of these are things that I noticed that we should look into, analyses, things to do, or thing sto try
- [ ] 1. `metadata/*metrics.json` changes, but none for `docs/metrics/` ([i](https://github.com/monarch-initiative/mondo-ingest/pull/573#discussion_r1643811305))
  - It seems to me that the latter should always happen if there are updates to the former. Bug?
- [ ] 2. `migrate-SOURCE.md` changes, but none for `slurp/SOURCE.tsv` ([i](https://github.com/monarch-initiative/mondo-ingest/pull/573/files))
  - It seems to me that the former should always happen if there are updates to the latter. Bug?
- [ ] 3. Sorting
  - Todo: We may be getting spurious diffs on a lot of files due to lack of record sorting. We should find if that's the case and fix.
  - `migrate*.md` and `unmapped*.md`: I think this is might be causing large diffs in these files as well ([i](https://github.com/monarch-initiative/mondo-ingest/pull/573/files)).
  - `lexmatch/README.md`: Needs sorting
- [ ] 4. Test: 2 builds back-to-back
  - Analysis: I think we should do a test and run a build back-to-back on the same branch. We should hope to see that there is no diff between the the results. I suppose we could do this either of 2 ways: (a) run the build, commit, run again, or (b) run on the same commit twice. Hopefully, in the time that these builds are running, no sources being `wget`ed will have been updated, otherwise that will sully the results.

## Additional information
We did a build on June 17th:
1. #571 
2. #572 
3. #573

<details><summary>Merge conflicts play any role?</summary>
<p>

However, I wonder if some of these issues might be caused by how I handled merge conflicts. I was going to merge develop into main (#572), but I got some conflicts. They were all data outputs, and since I'd just run a build on develop, I considered develop to be authoritative, and so I used that version of the file in all cases. These were the conflicts:

```
src/ontology/external/nando-mappings.robot.owl
src/ontology/external/nord.robot.owl
src/ontology/external/ordo-subsets.robot.owl
src/ontology/imports/omo_import.owl
src/ontology/imports/ro_import.owl
src/ontology/lexmatch/README.md
src/ontology/metadata/doid-metrics.json
src/ontology/metadata/gard-metrics.json
src/ontology/metadata/icd10cm-metrics.json
src/ontology/metadata/icd10who-metrics.json
src/ontology/metadata/icd11foundation-metrics.json
src/ontology/metadata/ncit-metrics.json
src/ontology/metadata/omim-metrics.json
src/ontology/metadata/ordo-metrics.json
src/ontology/reports/component_signature-omim.tsv
src/ontology/reports/mirror_signature-omim.tsv
src/ontology/reports/omim_mapping_status.tsv
src/ontology/reports/omim_unmapped_terms.tsv
src/ontology/slurp/omim.tsv
src/ontology/unmapped/omim-unmapped.owl
```

</p>
</details>
