### ISSUE TITLE
MedGen ingest

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo-ingest#6]
## Overview
Create MedGen ingest.

## Subtask list
- [x] 1. Create an ingest repo according to the principles outlined in #2, like you did for omim _(defunct)_
- [x] 2. Create a `make all` pipeline that generates medgen.owl as a resource _(defunct)_
- [x] 3. Fiddle `medgen` into the mondo-ingest pipeline here in this repo, and make sure that mapping, slurping etc works fine _(defunct)_
- [x] 4. Take any mappings `medgen` already has and convert them to SSSOM and attach them to the release _(defunct)_
- [ ] 5. https://github.com/monarch-initiative/mondo-ingest/issues/193

## Related
- #378 
- #193 
- #414

**Comment by joeflack4** [comment]
@matentzn @twhetzel I've checked off 1-4 here as complete, because they are now defunct.

Regarding (2), we don't have a `medgen.owl`, but we do have some `.obo` outputs in [the releases](https://github.com/monarch-initiative/medgen/releases).

Regarding (4), I think we've opted not to have a SSSOM created (on our side, at least), but we do create a robot template (see [releases](https://github.com/monarch-initiative/medgen/releases)).

Question @matentzn @twhetzel. Since 1-4 are done/defunct, only (5) remains, which simply links to #193.

So I think we should close this issue and just leave #193 open. I'm gonna do that now.

---

I also think we should close #193 and replace it with whatever the current issue(s) are, which I think are just #19 and working w/ the MedGen team to have them help us produce mappings to ingest.
