### ISSUE TITLE
Grouping: `omimFormerly`, `omimIncluded`, & `includedEntryInOMIM`

### ISSUE THREAD

**Issue by joeflack4** [monarch-initiative/mondo-ingest#715]
## Sub-tasks
- [ ] "Included" Decide if we want just want 1 property or 2
  - [ ] If just 1, which spelling to use?
- [ ] Ensure that how we're using these properties is correct
  - Joe thought they were best as synonym types (Nico seems ambivalent), but we're currently using them as annotation properties, I think.

## Sub-issues
- [x] https://github.com/monarch-initiative/omim/pull/168
- [ ] https://github.com/monarch-initiative/omim/pull/167
- [ ] https://github.com/monarch-initiative/mondo-ingest/pull/698
- [ ] https://github.com/monarch-initiative/mondo/pull/8235

**Comment by matentzn** [comment]
Just to reiterate:

```
[Term]
id: NI:CO
synonym: "Big G" EXACT ["MONDO:IncludedEntryInOMIM"]
```

Is something very different from 

```
[Term]
id: NI:CO
synonym: "Big G" OMIM_INCLUDED EXACT []
```

Do not mix these two things up! The first case is _source evidence_. The second case is a synonym type property!

**Comment by joeflack4** [comment]
Nico says this is bad:
a omoim_inclded true
a included_entry_in_omim true

Do this:
synonym: "Big G" EXACT ["MONDO:IncludedEntryInOMIM"]
- obo in owl source property

Want to do this way:
```

            add_triple_and_optional_annotations(graph, omim_uri, oboInOwl.hasExactSynonym, title,
                [oboInOwl.source, Literal('MONDO:includedEntryInOMIM')])

            add_triple_and_optional_annotations(graph, omim_uri, oboInOwl.hasExactSynonym, title,
                [oboInOwl.hasSynonymType, URIRef(MONDONS['omim_included'])])  # TODO: Needs the synonym type declaration
```
